/*
 * Copyright (c) 2003 Drew Frezell
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.frezell.icfp.viewer.util;

import java.awt.*;

/**
 *
 * @author Drew Frezell
 * @version $Revision: 1.3 $
 */
public final class Colormap {
    Color c;
    public static final int BITS = 8;
    public static final int SIZE = 256;
    public static final byte[] MAP = {
/*0x00*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x10*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x20*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 255, (byte) 255,     // finish line
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x30*/(byte) 55,  (byte) 55,  (byte) 55,      // grey0
        (byte) 71,  (byte) 71,  (byte) 71,      // grey1
        (byte) 87,  (byte) 87,  (byte) 87,      // grey2
        (byte) 103, (byte) 103, (byte) 103,     // grey3
        (byte) 119, (byte) 119, (byte) 119,     // grey4
        (byte) 135, (byte) 135, (byte) 135,     // grey5
        (byte) 151, (byte) 151, (byte) 151,     // grey6
        (byte) 167, (byte) 167, (byte) 167,     // grey7
        (byte) 183, (byte) 183, (byte) 183,     // grey8
        (byte) 200, (byte) 200, (byte) 200,     // grey9
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x40*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x50*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x60*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 255,     // blue
        (byte) 0,   (byte) 255, (byte) 255,     // cyan
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 255, (byte) 0,       // green
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 255, (byte) 0,   (byte) 255,     // magenta
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x70*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 255, (byte) 0,   (byte) 0,       // red
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 255, (byte) 255, (byte) 255,     // white
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 255, (byte) 255, (byte) 0,       // yellow
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x80*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0x90*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xa0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xb0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xc0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xd0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xe0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
/*0xf0*/(byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
        (byte) 0,   (byte) 0,   (byte) 0,
    };
}
